#!/bin/bash
BPurple='\033[1;35m'
Color_Off='\033[0m' 

set -e

# Clone dotfiles
echo -e "${BPurple}copying dotfiles 💎${Color_Off}"
clone_path="${clone_path:-"${HOME}/dotfiles"}"
# This is used to locally develop the install script.
if [ "${DEBUG}" == "1" ]; then
    cp -R "${PWD}/." "${clone_path}"
else
    git clone https://github.com/joshwrn/dotfiles "${clone_path}"
fi
rsync -a "${clone_path}/." "${HOME}"

sudo apt-get update && sudo apt-get install -y fzf

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || true
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k || true

 cat << EOF >> "${HOME}"/.bashrc
 zsh
EOF

# Done!
echo -e "${BPurple}Success! Restart terminal to get started. 🚀${Color_Off}"
exit 0
